Neos:
  Flow:
    http:
      middlewares:
        'Wwwision.Renderlets.Provider:Endpoint':
          position: 'after routing'
          middleware: Wwwision\Renderlets\Provider\Http\Middleware
  Neos:
    fusion:
      autoInclude:
        'Wwwision.Renderlets.Provider': true
